version: 0.0
os: linux
files:
  - source: /login.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 500
      runas: root
    - location: scripts/start_server.sh
      timeout: 500
      runas: root