version: 0.0
os: linux
files:
  - source: /
    destination: /root/destination/directory
hooks:
  ApplicationStop:
    - location: scripts/deregister_from_elb.sh
    - location: scripts/stop_httpd.sh
  ApplicationStart:
    - location: scripts/start_httpd.sh
    - location: scripts/register_with_elb.sh
